### ISSUE TITLE
Failed authenticated fetch of privately readable Solid documents

### ISSUE THREAD

**Issue by kezike** [kezike/solid-pg#1]
I am having issues loading privately readable data from my Solid account (such as data in `/inbox/`) into the application. An example of this can be viewed by executing the following steps:

- Navigate to local `solid-pg` directory
- Execute `npm install`
- Execute `npm start`
- Launch application at location returned by the previous command (ie. "http://localhost:8080/")
- Enter URI of publicly readable document, such as profile document or document in `/public/`
- Previous command should display content with no problem
- Enter URI of privately readable document, such as document in `/inbox/`
- Previous command should return `401 Unauthorized` message in console

Thanks in advance for your help!

**Comment by RubenVerborgh** [comment]
The code currently says:

```
<script src="./app/dist/app.bundle.js" charset="utf-8"></script>
```

but I corrected this to

```
<script src="./app.bundle.js" charset="utf-8"></script>
```

Your dist might have been outdated.

**Comment by RubenVerborgh** [comment]
Found the bug: you're using an antique version of the popup, which contains an old version of solid-auth-client. Fix in c5ed2ddc8963c54a705083c68d1b1d45bd90432f.

**Comment by kezike** [comment]
Wow, you're right! I had run `solid-auth-client generate-popup` so long ago with an older version of `solid-auth-client` and I have just been reusing that same cached version of `popup.html` for all of my projects. Thanks very much for noticing this, as I am now able to fetch properly! This is a learning moment for me to reuse cautiously, as older content may harbor deprecated artifacts from the past.

**Comment by RubenVerborgh** [comment]
It also shows that we have too many moving parts; a too large part of solid-auth-client is in the popup. See https://github.com/solid/solid-auth-client/issues/88
